# Generated by Django 5.2.7 on 2025-10-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='updated_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='updated_by',
            new_name='uploaded_by',
        ),
    ]
