# Generated by Django 5.2.7 on 2025-10-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_updated_at_attachment_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lecture',
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course'),
            preserve_default=False,
        ),
    ]
